---
- name: Simple ansible playbook
  hosts: all
  become: yes
  tasks:
    - name: Create/update file
      copy:
        content: "Version applied at {{ ansible_date_time.iso8601 }}"
        dest: /tmp/deploy.version
